/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to C Translator
  File name: RealtimeNetMsg.h
  Source: D:\wl\code\cyclonedds\install\bin\RealtimeNetMsg.idl
  Cyclone DDS: V0.10.4

*****************************************************************/
#ifndef DDSC_REALTIMENETMSG_H
#define DDSC_REALTIMENETMSG_H

#include "dds/ddsc/dds_public_impl.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifndef DDS_SEQUENCE_CHAR_DEFINED
#define DDS_SEQUENCE_CHAR_DEFINED
typedef struct dds_sequence_char
{
  uint32_t _maximum;
  uint32_t _length;
  char *_buffer;
  bool _release;
} dds_sequence_char;

#define dds_sequence_char__alloc() \
((dds_sequence_char*) dds_alloc (sizeof (dds_sequence_char)));

#define dds_sequence_char_allocbuf(l) \
((char *) dds_alloc ((l) * sizeof (char)))
#endif /* DDS_SEQUENCE_CHAR_DEFINED */

typedef struct RealtimeNetData_Msg
{
  int32_t offset;
  dds_sequence_char data;
} RealtimeNetData_Msg;

extern const dds_topic_descriptor_t RealtimeNetData_Msg_desc;

#define RealtimeNetData_Msg__alloc() \
((RealtimeNetData_Msg*) dds_alloc (sizeof (RealtimeNetData_Msg)));

#define RealtimeNetData_Msg_free(d,o) \
dds_sample_free ((d), &RealtimeNetData_Msg_desc, (o))

#ifdef __cplusplus
}
#endif

#endif /* DDSC_REALTIMENETMSG_H */
